### ISSUE TITLE
Better (I guess)

### ISSUE THREAD

**Issue by 0u44** [Zacky2613/ytdownload#1]
hello, i saw this repo and liked it so i kinda made it better by adding an intro and other cool stuff... go cheak it out here >> https://github.com/CPScript/Video-Downloader

**Comment by Zacky2613** [comment]
Your project looks super cool! I will look more into later when I have the time later today

**Comment by Zacky2613** [comment]
Hey man, just wondering but where did the project go? @CPScript

**Comment by 0u44** [comment]
yeah... i took it down bc i dont wanna have copyright law enforcers attack me... i also gave up on editing it, would take to long
